### ISSUE TITLE
PTM Review Feature List

### ISSUE THREAD

**Issue by BCrawfordScott** [nkuek/band-together#1]
Great work team , a couple of notes:

- [x]  #3 Songs
   - [x] Remove the term 'Posts' (although it's synonymous with song, the language is confusing)
   - [x] Logged in users can create a song
   - [x] Songs have a title, album, and artist, and song url
** Alternaitvely, you could change the Song entitiy to a SongPost entity and allow Users to have-many SongPosts, but this is really just semantics at that point **

Nice work :+1:

**Comment by joshsomthin** [comment]
Updated wiki to address these concerns.
