### ISSUE TITLE
Database Schema Review

### ISSUE THREAD

**Issue by BCrawfordScott** [nkuek/band-together#2]
Great work team, a couple of suggestions:

- [ ] Songposts
   - [ ] Align on authorId vs userId
   - [ ] Rename `userInput` - perhaps, is this meant to be the `body` of the post?
- [ ] Notes: rename `userInput`  - perhaps this is meant to be the `body` of the note?  

Potential bonus: create `genre`, `song`, and `artist` tables that a songPost will reference.  This will make them much easier to and faster to use for search. But, don't do this until it's bonus time.

**Comment by joshsomthin** [comment]
made appropriate corrections, and will revisit potential bonus when core features are implemented.
